
# Tugas 2 Setelah UTS - Berpikir Komputasional

```plaintext
Nama: Edgrant Henderson Suryajaya
NPM: 2206025016
```

In [ ]:
# 1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

x = 2
y = 3
del x

In [5]:
## 2. Write a line of code that generates the following error:
## NameError: name 'x' is not defined

x

NameError: name 'x' is not defined

In [ ]:
## 3. Let x = 10 and y = 3. Write a line of code that will make each of the following assignments.

'''
* u = x + y
* v = xy
* w = x/y
* z = sin(x)
* r = 8sin(x)
* s = 5sin(xy)
* p = x**y
'''

import math

x = 10
y = 3
u = x + y
v = x * y
w = x / y
z = math.sin(x)
r = 8 * math.sin(x)
s = 5 * math.sin(x * y)
p = x ** y

In [ ]:
## 4. Show all the variables in the Jupyter notebook after you finish problem 3.
print(u, v, w, z, r, s, p)

In [9]:
## 5. Assign string ‘123’ to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.

S = '123'
N = float(S)
print(type(S), type(N))

<class 'str'> <class 'float'>


In [ ]:
## 6. Assign the string ‘HELLO’ to the variable s1 and the string ‘hello’ to the variable s2. Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the lower method is used on s1. Use the == operator to show that s1 and s2 are equal if the upper method is used on s2.

s1 = 'HELLO'
s2 = 'hello'

print(s1 == s2)
print(s1.lower() == s2.lower())

False
True


In [12]:
## 7. Use the print function to generate the following strings.

'''
* The world ‘Engineering’ has 11 letters.
* The word ‘Book’ has 4 letters.
'''

print(f'The word "Engineering" has {len("Engineering")} letters.')
print(f'The word "Book" has {len("Book")} letters.')

The word "Engineering" has 11 letters.
The word "Book" has 4 letters.


In [13]:
## 8. Check if ‘Python’ is in ‘Python is great!’.

print('Python' in 'Python is great!')

True


In [14]:
## 9. Get the last word ‘great’ from ‘Python is great!’

print('Python is great!'.split()[-1])

great!


In [15]:
## 10. Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15, 4]


In [17]:
## 11. Sort the list_a in problem 10 in ascending order.

list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


In [19]:
## 12. Turn ‘Python is great!’ to a list.

list_python_is_great = list('Python is great!')
print(list_python_is_great)

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']


In [20]:
## 13. Create one tuple with element ‘One’, 1 and assign it to tuple_a

tuple_a = ('One', 1)
print(tuple_a)

('One', 1)


In [21]:
## 14. Get the 2nd element in the tuple_a in problem 13.

print(tuple_a[1])

1


In [ ]:
## 14a. Get the unique element from (2, 3, 2, 3, 1, 2, 5).

unique_elements = set((2, 3, 2, 3, 1, 2, 5))
print(unique_elements)

{1, 2, 3, 5}


In [ ]:
## 15. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:

'''
* union of `set_a` and `set_b`
* intersection of `set_a` and `set_b`
* difference of `set_a` to `set_b` using the `difference()` method
'''

set_a = {2, 3, 2}
set_b = {1, 2, 3}

print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


In [ ]:
## 16. Create a dictionary that has the keys ‘A’, ‘B’, ‘C’ with values ‘a’, ‘b’, ‘c’ individually. Print all the keys in the dictionary.

dict_a = {'A': 'a', 'B': 'b', 'C': 'c'}
print(dict_a.keys())

dict_keys(['A', 'B', 'C'])


In [ ]:
## 17. Check if key ‘B’ is in the dictionary defined in problem 17.

print('B' in dict_a)

True


In [ ]:
## 18. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.

'''
* u = x + y
* v = xy
* w = x/y
* z = sin(x)
* r = 8sin(x)
* s = 5sin(xy)
* p = x**y
'''

x = [1, 4, 3, 2, 9, 4]
y = [2, 3, 4, 1, 2, 3]

for i in range(len(x)):
    u = x[i] + y[i]
    v = x[i] * y[i]
    w = x[i] / y[i]
    z = math.sin(x[i])
    r = 8 * math.sin(x[i])
    s = 5 * math.sin(x[i] * y[i])
    p = x[i] ** y[i]

    print(f"u: {u}, v: {v}, w: {w}, z: {z}, r: {r}, s: {s}, p: {p}")


u: 3, v: 2, w: 0.5, z: 0.8414709848078965, r: 6.731767878463172, s: 4.546487134128409, p: 1
u: 7, v: 12, w: 1.3333333333333333, z: -0.7568024953079282, r: -6.054419962463426, s: -2.6828645900021746, p: 64
u: 7, v: 12, w: 0.75, z: 0.1411200080598672, r: 1.1289600644789377, s: -2.6828645900021746, p: 81
u: 3, v: 2, w: 2.0, z: 0.9092974268256817, r: 7.274379414605454, s: 4.546487134128409, p: 2
u: 11, v: 18, w: 4.5, z: 0.4121184852417566, r: 3.2969478819340527, s: -3.754936233858381, p: 81
u: 7, v: 12, w: 1.3333333333333333, z: -0.7568024953079282, r: -6.054419962463426, s: -2.6828645900021746, p: 64


In [ ]:
## 19. Generate an array with size 100 evenly spaced between -10 to 10 using linspace function in Numpy.

import numpy as np
x = np.linspace(-10, 10, 100)
print(x)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

In [ ]:
## 20. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.

array_a = np.array([-1, 0, 1, 2, 0, 3])
array_filter = array_a[array_a > 0]
print(array_filter)

[1 2 3]


In [ ]:
## 21. Create an array

'''
3 5 3
2 2 5
3 8 9
'''

# and calculate the transpose of the array.

array_before = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
array_after = array_before.T
print(array_after)

[[3 2 3]
 [5 2 8]
 [3 5 9]]


In [ ]:
## 22. Create a zero array with size (2, 4).

zero_array = np.zeros((2, 4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
## 23. Change the 2nd column in the above array to 1.

zero_array[:, 1] = 1
print(zero_array)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
## 24. Write a cell magic to clear all the variables in the Jupyter notebook

del globals()['x']
del globals()['y']
del globals()['u']
del globals()['v']
del globals()['w']
del globals()['z']
del globals()['r']
del globals()['s']
del globals()['p']
del globals()['S']
del globals()['N']
del globals()['s1']
del globals()['s2']
del globals()['list_a']
del globals()['list_python_is_great']
del globals()['tuple_a']
del globals()['unique_elements']
del globals()['set_a']
del globals()['set_b']
del globals()['dict_a']
del globals()['array_a']
del globals()['array_before']
del globals()['array_after']
del globals()['zero_array']

In [ ]:
## 25. Print “I love Python” using Python Shell.

# Saya menggunakan windows
!python -c "print('I love Python')"

I love Python


In [ ]:
## 26. Print “I love Python” by typing it into a .py file and run it from command line.

# Saya menggunakan windows
!echo print('I love Python') > love_python.py
!python love_python.py

I love Python


In [ ]:
## 27. Type import antigravity in the Ipython Shell, it will take you to xkcd and see the awesome Python.

# Saya menggunakan windows
!python -c "import antigravity"

In [ ]:
## 28. Launch a new Jupyter notebook server in a folder called “excercise” and create a new Python notebook with the name “excercise_1”, then you can do the rest of the problems within this notebook.

A subdirectory or file excercise already exists.


In [ ]:
## 29. Compute the area of a triangle with base 10 and height 12. Recall that the area of a triangle is half the base times the height.

base = 10
height = 12
area = 0.5 * base * height
print(f"Area of triangle: {area}")

Area of triangle: 60.0


In [ ]:
## 30. Compute the surface area and volume of a cylinder with radius 5 and height 3.

import math

radius = 5
height = 3
surface_area = 2 * math.pi * radius * (radius + height)
volume = math.pi * radius**2 * height
print(f"Surface area of cylinder: {surface_area}")
print(f"Volume of cylinder: {volume}")

Surface area of cylinder: 251.32741228718345
Volume of cylinder: 235.61944901923448


In [ ]:
## 31 dan 32. Compute the slope between the points (3,4) and (5,9) Recall that the slope between points (x1,y1) and (x2,y2) is y2−y1x2−x1 .

x1, y1 = 3, 4
x2, y2 = 5, 9
slope = (y2 - y1) / (x2 - x1)
print(f"Slope between points (3,4) and (5,9): {slope}")

Slope between points (3,4) and (5,9): 2.5


In [49]:
## 33. Compute the distance between the points (3,4) and (5,9). Recall that the distance between points in two dimensions 

x1, y1 = 3, 4
x2, y2 = 5, 9
distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
print(f"Distance between points (3,4) and (5,9): {distance}")

Distance between points (3,4) and (5,9): 5.385164807134504


In [ ]:
## 34. Use Python’s factorial function to compute 6!

import math
factorial_6 = math.factorial(6)
print(f"6! = {factorial_6}")

6! = 720


In [50]:
## 35. A year is considered to be 365 days long. However, a more exact figure is 365.24 days. As a consequence, if we held to the standard 365-day year, we would gradually lose that fraction of the day over time, and seasons and other astronomical events would not occur as expected. A leap year is a year that has an extra day, February 29, to keep the timescale on track. Leap years occur on years that are exactly divisible by 4, unless it is exactly divisible by 100, unless it is divisible by 400. For example, the year 2004 is a leap year, the year 1900 is not a leap year, and the year 2000 is a leap year. Compute the number of leap years between the years 1500 and 2010.


leap_years = []
for year in range(1500, 2011):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        leap_years.append(year)
print(f"Leap years between 1500 and 2010: {leap_years}")

Leap years between 1500 and 2010: [1504, 1508, 1512, 1516, 1520, 1524, 1528, 1532, 1536, 1540, 1544, 1548, 1552, 1556, 1560, 1564, 1568, 1572, 1576, 1580, 1584, 1588, 1592, 1596, 1600, 1604, 1608, 1612, 1616, 1620, 1624, 1628, 1632, 1636, 1640, 1644, 1648, 1652, 1656, 1660, 1664, 1668, 1672, 1676, 1680, 1684, 1688, 1692, 1696, 1704, 1708, 1712, 1716, 1720, 1724, 1728, 1732, 1736, 1740, 1744, 1748, 1752, 1756, 1760, 1764, 1768, 1772, 1776, 1780, 1784, 1788, 1792, 1796, 1804, 1808, 1812, 1816, 1820, 1824, 1828, 1832, 1836, 1840, 1844, 1848, 1852, 1856, 1860, 1864, 1868, 1872, 1876, 1880, 1884, 1888, 1892, 1896, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008]
